### ISSUE TITLE
Use the Rich library for improved terminal UX for Node and Hub interaction

### ISSUE THREAD

**Issue by kaushikb11** [NapthaAI/naptha-sdk#56]
## Description:
Currently, the CLI uses a mix of print statements and tabulate for displaying information. We should standardize on [Rich library](https://github.com/Textualize/rich) for all CLI interactions to provide a more modern, readable, and user-friendly interface.

### Current Implementation:
- Basic print statements for status messages
- Tabulate for data tables (see list_nodes, list_personas)
- Inconsistent styling across different commands

### Benefits of using Rich:
1. Better table formatting with automatic width adjustment
2. Built-in support for:
   - Color coding and styling
   - Progress bars
   - Status indicators
   - Tree structures
   - Syntax highlighting
   - Markdown rendering
   
For instance:
<img width="1103" alt="Screenshot 2024-12-10 at 6 30 45 PM" src="https://github.com/user-attachments/assets/45b1dfea-0fab-40b7-8d23-cd72de3a31a9">

**Comment by richardblythman** [comment]
This has been added to the feat/knowledge-base branch @kaushikb11. We will be merging shortly. Thanks for the great suggestion!

**Comment by richardblythman** [comment]
Merged with #67
